<?php

define('CROWDSEC_PLUGIN_PATH', __DIR__);
define('CROWDSEC_PLUGIN_URL', plugin_dir_url(__FILE__));

define('CROWDSEC_BOUNCING_LEVEL_DISABLED', "0");
define('CROWDSEC_BOUNCING_LEVEL_FLEX', "1");
define('CROWDSEC_BOUNCING_LEVEL_NORMAL', "2");
define('CROWDSEC_BOUNCING_LEVEL_PARANOID', "3");

define('CROWDSEC_CACHE_SYSTEM_PHPFS', "0");
define('CROWDSEC_CACHE_SYSTEM_REDIS', "1");
define('CROWDSEC_CACHE_SYSTEM_MEMCACHED', "2");

define('CROWDSEC_CAPTCHA_TECHNOLOGY_LOCAL', "0");
define('CROWDSEC_CAPTCHA_TECHNOLOGY_RECAPTCHA', "1");

define('CROWDSEC_BOUNCER_USER_AGENT', "Wordpress CrowdSec Bouncer/0.0.1");// TODO P1 SET THE CORRECT VERSION ON BUILD
