on:
  workflow_dispatch:

permissions:
  contents: read

name: Documentation links
jobs:
  markdown-test:
    name: Markdown files test
    runs-on: ubuntu-latest
    steps:

      - name: Clone sources
        uses: actions/checkout@v4
        with:
          path: extension

      - name: Launch localhost server
        run: |
          sudo npm install --global http-server
          http-server ./extension &

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Check links in Markdown files
        run: |
          gem install awesome_bot
          cd extension
          awesome_bot --files README.md --allow-dupe --allow 401 --skip-save-results --white-list ddev.site --base-url http://localhost:8080/
          awesome_bot docs/*.md --skip-save-results --allow-dupe --allow 401 --white-list ddev.site,your-wordpress-url,crowdsec:8080 --base-url http://localhost:8080/docs/
